# Generated by Django 3.2 on 2022-03-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_customer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='full_phone_num',
            field=models.CharField(default='', max_length=15),
        ),
    ]
